name: SAST

on:
  push:
    branches:
      - main

permissions:
  contents: read
  issues: write

jobs:
  bandit:  # reqs: https://docs.github.com/en/code-security/how-tos/find-and-fix-code-vulnerabilities/configure-code-scanning/configuring-default-setup-for-code-scanning
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
    steps:
      - name: Perform Bandit Analysis
        uses: PyCQA/bandit-action@v1.0.1
        with:
          targets: "."
          python-version: "3.11"

  semgrep:
    runs-on: ubuntu-latest
    # Skip any PR created by dependabot to avoid permission issues
    if: (github.actor != 'dependabot[bot]')

    steps:
      - uses: actions/checkout@v6
      - name: Semgrep - Lightweight SAST to find bugs and enfource code standards
        uses: returntocorp/semgrep-action@v1
        with:
          config: >- # more at semgrep.dev/explore
            p/security-audit
            p/secrets

# dependency-check isn't the best tool for Python applications
  # depcheck:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: 
  #     - uses: actions/checkout@v6
  #     - name: Depcheck tool
  #       uses: dependency-check/Dependency-Check_Action@main
  #       id: Depcheck
  #       with:
  #         project: 'insecure-acebook'
  #         path: '.'
  #         format: 'HTML'
  #         args: >
  #           --failOnCVSS 7
  #           --enableRetired
  #     - name: Upload Test results
  #       uses: actions/upload-artifact@main
  #       with:
  #         name: Depcheck report
  #         path: ${{github.workspace}}/reports

  audit-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pypa/gh-action-pip-audit@v1.1.0
        with:
          inputs: requirements.txt
          ignore-vulns: |
            PYSEC-2022-42969